# Generated by Django 5.1.3 on 2024-12-03 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 3, 17, 59, 20, 24572, tzinfo=datetime.timezone.utc)),
        ),
    ]
