# Generated by Django 5.1.3 on 2024-12-03 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0002_alter_streak_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
