# Generated by Django 5.1.3 on 2024-12-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0004_alter_streak_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='has_ended',
            field=models.BooleanField(default=False),
        ),
    ]
