# Generated by Django 5.1.3 on 2024-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0005_streak_has_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='already_increased',
            field=models.BooleanField(default=False),
        ),
    ]
