# Generated by Django 5.1.3 on 2024-12-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0006_streak_already_increased'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
