# Generated by Django 5.1.3 on 2024-12-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0007_streak_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
