# Generated by Django 5.1.3 on 2024-12-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0008_alter_streak_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='has_ended',
        ),
    ]
