# Generated by Django 5.1.3 on 2024-12-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0010_rename_date_added_streak_date_started_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='date_started',
            field=models.DateField(auto_now_add=True),
        ),
    ]
