# Generated by Django 5.1.3 on 2024-12-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0011_alter_streak_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='date_started',
            field=models.DateField(auto_now=True),
        ),
    ]
