# Generated by Django 5.1.3 on 2024-12-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0012_alter_streak_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
